### PR TITLE
Add (lost) reading from VERITAS_DATA_DIR

### PR DESCRIPTION
**Pull request by GernotMaier**
This PR recovers the functionality to read VBF files for the data analysis from `$VERITAS_DATA_DIR`.

Note that preference is still given to `$VERITAS_DATA_DIR_2`, and `$VERITAS_DATA_DIR` is the fall back option (this is an optimized setup for the pre-processing at DESY.

### CODE REVIEW

**Comment by GernotMaier** [comment]
@steob92 - can you try again?

**Comment by GernotMaier** [comment]
Wait,.... I pushed to the wrong branch.....

**Comment by GernotMaier** [comment]
@steob92 - now, please try again.

**Comment by steob92** [comment]
I'm still having issues. This is likely related to #92 (I'm using --cleanenv) I'll expand on this in the issue thread:

```
Scratch dir: /raid/jacko/obriens/VERITAS/tmpdir/64080
APPTAINER MOUNT:  --bind /raid/jacko/obriens/EDv490/Eventdisplay_AnalysisFiles_VTS:/opt/VERITAS_EVNDISP_AUX_DIR  --bind /raid/jacko/obriens/VERITAS/ebl_data_dir/:/opt/VERITAS_DATA_DIR  --bind  /raid/jacko/obriens/VERITAS/ED_data:/opt/VERITAS_USER_DATA_DIR  --bind /raid/jacko/obriens/VERITAS/ebl_data_dir//DBTEXT:/opt/DBTEXT  --bind /raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490/:/opt/ODIR  --bind /raid/jacko/obriens/VERITAS/tmpdir/64080:/opt/TEMPDIR
APPTAINER SYS: singularity exec --no-mount bind-paths --cleanenv --env VERITAS_DATA_DIR=/opt/VERITAS_DATA_DIR,VERITAS_EVNDISP_AUX_DIR=/opt/VERITAS_EVNDISP_AUX_DIR,VERITAS_USER_DATA_DIR=/opt/VERITAS_USER_DATA_DIR,TEMPDIR=/opt/TEMPDIR,CALDIR=/opt/ODIR,LOGDIR=/opt/ODIR  --bind /raid/jacko/obriens/EDv490/Eventdisplay_AnalysisFiles_VTS:/opt/VERITAS_EVNDISP_AUX_DIR  --bind /raid/jacko/obriens/VERITAS/ebl_data_dir/:/opt/VERITAS_DATA_DIR  --bind  /raid/jacko/obriens/VERITAS/ED_data:/opt/VERITAS_USER_DATA_DIR  --bind /raid/jacko/obriens/VERITAS/ebl_data_dir//DBTEXT:/opt/DBTEXT  --bind /raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490/:/opt/ODIR  --bind /raid/jacko/obriens/VERITAS/tmpdir/64080:/opt/TEMPDIR /raid/jacko/obriens/singularityLib/eventdisplay_v4_v490.7.sif /opt/EventDisplay_v4/
Using run parameter file EVNDISP.reconstruction.runparameter.AP.v4x
UNPACKING DBTEXT from /raid/jacko/obriens/VERITAS/ebl_data_dir//DBTEXT
DBTEXT FILE for 64080 /raid/jacko/obriens/VERITAS/ebl_data_dir//DBTEXT/6/64080.tar.gz
unpacking 64079
DBTEXT FILE for 64079 /raid/jacko/obriens/VERITAS/ebl_data_dir//DBTEXT/6/64079.tar.gz
/raid/jacko/obriens/VERITAS/tmpdir/64080/DBTEXT/6/64079/64079.laserrun
DBTEXT directory total 0
drwxr-xr-x 4 obriens veritas 44 Jun  3 10:22 6
-dbtextdirectory /raid/jacko/obriens/VERITAS/tmpdir/64080/DBTEXT -epochfile VERITAS.Epochs.runparameter
RUN 64080 /raid/jacko/obriens/VERITAS/tmpdir/64080/DBTEXT/6//64080/64080.runinfo d20121013
total 0
drwxr-xr-x 4 obriens veritas 44 Jun  3 10:22 6
CVBF FILE FOUND - data dir: /raid/jacko/obriens/VERITAS/ebl_data_dir/ 
/var/lib/slurm/slurmd/job235189/slurm_script: line 59: apptainer: command not found
RUN64080 PEDLOG /raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490//64080.ped.log
Telescope combination saved in the DB is analyzed (default)
/var/lib/slurm/slurmd/job235189/slurm_script: line 59: apptainer: command not found
RUN64080 TZEROLOG /raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490//64080.tzero.log
/var/lib/slurm/slurmd/job235189/slurm_script: line 59: apptainer: command not found
RUN64080 EVNDISPLOG /raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490//64080.log
'/raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490//64080.log' -> '/raid/jacko/obriens/VERITAS/tmpdir/64080/64080.log'
WARNING: Ignoring unknown mount type 'bind-paths'
SysError in <TFile::TFile>: file /raid/jacko/obriens/VERITAS/tmpdir/64080/64080.root can not be opened No such file or directory
Error: root file not found: /raid/jacko/obriens/VERITAS/tmpdir/64080/64080.root
'/raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490//64080.ped.log' -> '/raid/jacko/obriens/VERITAS/tmpdir/64080/64080.ped.log'
WARNING: Ignoring unknown mount type 'bind-paths'
SysError in <TFile::TFile>: file /raid/jacko/obriens/VERITAS/tmpdir/64080/64080.root can not be opened No such file or directory
Error: root file not found: /raid/jacko/obriens/VERITAS/tmpdir/64080/64080.root
'/raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490//64080.tzero.log' -> '/raid/jacko/obriens/VERITAS/tmpdir/64080/64080.tzero.log'
WARNING: Ignoring unknown mount type 'bind-paths'
SysError in <TFile::TFile>: file /raid/jacko/obriens/VERITAS/tmpdir/64080/64080.root can not be opened No such file or directory
Error: root file not found: /raid/jacko/obriens/VERITAS/tmpdir/64080/64080.root
cp: cannot stat '/raid/jacko/obriens/VERITAS/tmpdir/64080/64080.root': No such file or directory
RUN64080 VERITAS_USER_DATA_DIR /raid/jacko/obriens/VERITAS/ED_data/analysis/Results/v490//64080.root
```

**Comment by GernotMaier** [comment]
really hard to debug without access - but aren't you worried about all the warnings that apptainer does not exist? I don't understand exactly why you get them, didn't you set the command to singularity?

**Comment by steob92** [comment]
I'm not worried, this is a scope issue when I alias. The line that complains is on the `apptainer inspect` image. If I change `apptainer inspect` to `singularity inspect` it removes the warning but the other issues remain.

**Comment by GernotMaier** [comment]
I am merging this branch now. The changes are fine with me (but still not sure if it solves the original problems).

**Pull request merged**
